---
version: "3"

tasks:
  build:
    desc: Build docker image
    preconditions:
    - sh: "which docker"
      msg: "kind {{.PATH_ERROR}}"
    cmds:
    - docker image build -t earn-pre:latest .
    - docker images

  run:
    desc: Run docker container
    preconditions:
    - sh: "which docker"
      msg: "kind {{.PATH_ERROR}}"
    cmds:
    - docker run -d --rm earn-pre:latest
    - docker ps
